services:
  - type: web
    name: pdf-api
    env: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: false
    build:
      nodeVersion: 20
